version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "./app/src:/var/www/html"
    ports:
      - "8090:80"
  db:
    image: mysql:5.7.43
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
      - ./database/data:/var/lib/mysql:rw
    ports:
      - "8191:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - UPLOAD_LIMIT=2G
    ports:
      - 8292:80